#Visualization project Supermarket_sales by Power BI: 
https://app.powerbi.com/view?r=eyJrIjoiYmZmN2YxYjktODJmOS00Mzg1LWJkZTEtNjMyZmU1ZDYyZTJmIiwidCI6ImNmNmJiYjI5LWYxNjUtNGUxYy04OWY5LTI4Y2JjZWE2ZTliNiIsImMiOjEwfQ%3D%3D
